### ISSUE TITLE
Checkbox doesn't work for server rendering

### ISSUE THREAD

**Issue by r0man** [aJchemist/rum-mdl#2]
Hello @aJchemist,

the checkbox component throws an exception when used in Clojure. I'm doing server side rendering and run into this issue. This works in ClojureScript, but throws an exception in Clojure. I'm also using rum `0.10.5`.

```
(mdl/checkbox {:label "hello"})

Wrong number of args (2) passed to: mdl/fn--51513

     AFn.java:  429  clojure.lang.AFn/throwArity
     AFn.java:   36  clojure.lang.AFn/invoke
     AFn.java:  156  clojure.lang.AFn/applyToHelper
     AFn.java:  144  clojure.lang.AFn/applyTo
     core.clj:  651  clojure.core/apply
     core.clj:  646  clojure.core/apply
     core.clj:  123  rum.core/build-defc/render
     core.clj:  116  rum.core/build-ctor/fn
  RestFn.java:  408  clojure.lang.RestFn/invoke
```

Btw., how do you work on this project? Do you use Emacs and jack-in?

I couldn't get that working and also the boot tasks throw exceptions. I get errors like 
- namespace 'cljs.source-map' not found
- clojure.lang.ExceptionInfo: No such var: string/index-of

Any ideas? 

r0man

**Comment by r0man** [comment]
Same problem for `mdl/snackbar`.

**Comment by ajchemist** [comment]
@r0man 

The problem is this.

``` clojure
(apply (fn [a] a) [1 2])
```

In clojurescript, this is fine, but not in clojure. 

For now I'm not sure what will be good fix. Do you have a good idea?

And I work on rum-mdl with `boot dev repl -s wait`. then `cider-connect`. or `C-u M-x cider-jack-in` for prompt custom nrepl server command.

**Comment by r0man** [comment]
Ok, wasn't aware I had to put BOOT_CLOJURE_VERSION=1.8.0 into my `boot.properties`. Now I can run the boot tasks. Looking into the checkbox problem.

**Comment by r0man** [comment]
@aJchemist I tried the latest changes. Works as expected. Thanks for looking into this!
